slide_data:
  default: "[]"
  json_schema: >-
    {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "minLength": 1
          },
          "description": {
            "type": "string",
            "minLength": 1
          },
          "logo_url": {
            "type": "string",
            "format": "url"
          },
          "background_image_url": {
            "type": "string",
            "format": "url"
          }
        },
        "additionalProperties": false
      }
    }
only_show_mobile_app:
  type: bool
  default: false
  description:
    en: "Only show on mobile app."
