only_show_mobile_app:
  type: bool
  default: false
  description:
    en: "Only show on mobile app."
number_of_slides:
  type: integer
  default: 3
  description:
    en: "Number of slides to show. (Max is 5)"
